on:
  issue_comment:
    types: [created]
name: Commands
jobs:
  style:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: testing
        run: echo '${{ steps.file_changes.outputs.files_modified}}'   
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - name: Install 
        run: yarn run prettier --write '**/*.{css,js,vue}'

      - name: commit
        run: |
          git add .
          git config --global user.email "bot@example.com"
          git config --global user.name "Bot"
          
          if [[ $(git diff --name-only --cached) != "" ]]; then  git commit -m 'automated syle update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
